packages:
    # all packages in direct subdirs of packages/
    - 'packages/@gyozo/admin'
    - 'packages/@gyozo/lib'
    - 'packages/@gyozo/publish'
    # all packages in subdirs of components/
    # - 'components/**'
    # exclude packages that are inside test directories
    # - '!**/test/**'
